source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.3.4"

group :development do
  gem 'annotate'
  gem 'capistrano'
  gem 'capistrano-rails'
  gem 'capistrano-rbenv'
  gem 'capistrano-bundler'
  gem 'capistrano-npm'
  gem 'capistrano-sidekiq'
  gem 'capistrano3-puma'
  gem "ed25519", ">= 1.2", "< 2.0", require: false
  gem "bcrypt_pbkdf", ">= 1.0", "< 2.0", require: false
end
